name: Lint

on: [push, pull_request]

permissions:
  contents: read  

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
      - uses: psf/black@4f1883b1f15305a0e83a7c87991f46292bf09f85  # 26.10.0
